allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@sanity/access-ui@6.13.2'
  - '@sanity/diff@6.13.2'
  - '@sanity/mutator@6.13.2'
  - '@sanity/schema@6.13.2'
  - '@sanity/types@6.13.2'
  - '@sanity/util@6.13.2'
  - '@sanity/validation@6.13.2'
  - sanity@6.13.2
