allowBuilds:
  esbuild: true
overrides:
  js-yaml@<3.15.2: '>=3.15.2'
  smol-toml@<1.8.0: '>=1.8.0'
  adm-zip@<0.6.1: '>=0.6.1'
  uuid@<11.1.1: '>=11.1.1'
minimumReleaseAgeExclude:
  - '@sanity/access-ui@6.13.2'
  - '@sanity/diff@6.13.2'
  - '@sanity/mutator@6.13.2'
  - '@sanity/schema@6.13.2'
  - '@sanity/types@6.13.2'
  - '@sanity/util@6.13.2'
  - '@sanity/validation@6.13.2'
  - sanity@6.13.2
  - adm-zip@0.6.1
